name: yamata_launcher
description: Yamata Launcher

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  animate_do: ^3.0.2
  provider: ^6.1.5+1
  permission_handler: ^11.0.1
  toast: ^0.3.0
  device_apps: ^2.2.0
  material_segmented_control: ^3.1.2
  shared_preferences: ^2.0.15
  http: ^1.2.0
  html: ^0.15.4
  share: ^2.0.4
  package_info_plus: ^8.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  collection: ^1.15.0
  skeletonizer: ^1.4.3
  sembast: ^3.7.1
  path_provider: ^2.1.4
  another_flushbar: ^1.12.32
  url_launcher: ^6.3.1
  file_picker: ^8.0.5
  flutter_local_notifications: 18.0.1
  android_intent_plus: ^5.3.1
  flutter_svg: ^2.1.0
  windows_notification: ^1.3.0
  archive: ^4.0.7
  media_scanner: ^2.2.0
  filesystem_picker:
    git:
      url: https://github.com/Iconica-Development/filesystem_picker.git
      path: package
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/icons/
      - assets/icons/consoles/
      - assets/svgs/
      - assets/bin/7z/
      - assets/bin/aria2c/

dependency_overrides:
  file: 6.1.4
  platform: 3.1.0